services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5007:5003"
    volumes:
      - data:/data
    depends_on:
      - mailbox

  mailbox:
    build:
      context: .
      dockerfile: Dockerfile.mailbox
    ports:
      - "5017:5013"
    volumes:
      - maildata:/data

volumes:
  data:
  maildata:
